/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    'boscheasycontrol adapter settings': {
        'en': 'Adapter settings for boscheasycontrol',
        'de': 'Adaptereinstellungen für boscheasycontrol',
        'ru': 'Настройки адаптера для boscheasycontrol',
        'pt': 'Configurações do adaptador para boscheasycontrol',
        'nl': 'Adapterinstellingen voor boscheasycontrol',
        'fr': "Paramètres d'adaptateur pour boscheasycontrol",
        'it': "Impostazioni dell'adattatore per boscheasycontrol",
        'es': 'Ajustes del adaptador para boscheasycontrol',
        'pl': 'Ustawienia adaptera dla boscheasycontrol',
        'zh-cn': 'boscheasycontrol的适配器设置'
    },
    'serial': {
        'en': 'Serial',
        'de': 'Serial',
        'ru': 'Serial',
        'pt': 'Serial',
        'nl': 'Serial',
        'fr': 'Serial',
        'it': 'Serial',
        'es': 'Serial',
        'pl': 'Serial',
        'zh-cn': 'Serial'
    },
    'accesskey': {
        'en': 'Access Key',
        'de': 'Access Key',
        'ru': 'Access Key',
        'pt': 'Access Key',
        'nl': 'Access Key',
        'fr': 'Access Key',
        'it': 'Access Key',
        'es': 'Access Key',
        'pl': 'Access Key',
        'zh-cn': 'Access Key'
    },
    'password': {
        'en': 'Password',
        'de': 'Password',
        'ru': 'Password',
        'pt': 'Password',
        'nl': 'Password',
        'fr': 'Password',
        'it': 'Password',
        'es': 'Password',
        'pl': 'Password',
        'zh-cn': 'Password'
    }
};
